import { schema } from "@schemas/main.schema";


export default (opts: schema) => `#Systemd service file for the Fluidd server
#This file has been automatically generated by klipper-deployer. Please do not edit it manually.

[Unit]
Description=Starts the fluidd UI on startup
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=${opts.install.user}
RemainAfterExit=yes
ExecStart=python3 -m http.server ${opts.services.fluidd!.port} --directory ${opts.install.base}/repos/fluidd 
Restart=always
RestartSec=10`