import { schema } from "../schemas/main.schema";


export default (opts: schema) => `#Systemd service file for the Mainsail server
#This file has been automatically generated by klipper-deployer. Please do not edit it manually.

[Unit]
Description=Starts the mainsail UI on startup
After=network.target

[Install]
WantedBy=multi-user.target

[Service]
Type=simple
User=${opts.install.user}
RemainAfterExit=yes
ExecStart=python3 -m http.server ${opts.services.mainsail!.port} --directory ${opts.install.base}/repos/mainsail 
Restart=always
RestartSec=10`